CREATE PROCEDURE QGPL/MyProc (
  IN STD_ID_IN CHAR(3)
)

DYNAMIC RESULT SETS 1
LANGUAGE SQL 
SPECIFIC QGPL/MyProc 

BEGIN 
  DECLARE C1 CURSOR FOR 
    SELECT  STD_ID, a.CLASS_ID, CLASS_DESC, TEACHER_ID, GRADE
    FROM    QGPL/STUDENT a, QGPL/CLASS b
    WHERE   STD_ID = STD_ID_IN and a.CLASS_ID = b.CLASS_ID;
  
  OPEN C1; 
END ;


CREATE TABLE QGPL/STUDENT (
STD_ID CHAR(3),
STD_NAME CHAR(20),
CLASS_ID CHAR(3),
GRADE CHAR(1)) ;

CREATE TABLE QGPL/CLASS (
CLASS_ID CHAR(3),
CLASS_DESC CHAR(20),
TEACHER_ID CHAR(3));


